on:
  push:
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  freebsd:
    runs-on: ubuntu-latest
    env:
      MAKEFLAGS: -j4
      OPENTURNS_NUM_THREADS: 2
      OMP_NUM_THREADS: 1
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: vmactions/freebsd-vm@v1
        with:
          envs: 'MAKEFLAGS OPENTURNS_NUM_THREADS OMP_NUM_THREADS'
          usesh: true
          prepare: |
            pkg install -y cmake git devel/llvm devel/swig devel/boost-all devel/onetbb textproc/libxml2
            pkg install -y math/lapack #science/hdf5 math/nanoflann math/spectra math/primesieve math/py-matplotlib
            pkg install -y math/SCIP devel/gdb
          run: |
            git config --global --add safe.directory .
            cmake -DCMAKE_INSTALL_PREFIX=~/.local -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=32 -DCMAKE_CXX_FLAGS="-Wall -Wextra -Wpedantic -Wshadow -Werror -D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE" -DSWIG_COMPILE_FLAGS="-O1 -Wno-shadow -Wno-unused-function" -DCMAKE_BUILD_TYPE=RelWithDebInfo . || exit 1
            cmake --build . --target install || exit 1
            ctest --output-on-failure --timeout 200 -R SCIP -E cppcheck -V -j4 --repeat after-timeout:2 --schedule-random || echo "NOPE"
            PYTHONPATH=~/.local/lib/python3.12/site-packages gdb -q batch -ex run -ex bt --args /usr/local/bin/python3.12 ./python/test/t_SCIP_std.py
