on:
  push:
  pull_request:
jobs:
  macos:
    runs-on: macos-latest
    env:
      LDFLAGS: -L/usr/local/opt/openblas/lib
      CPPFLAGS: -I/usr/local/opt/openblas/include
    steps:
    - uses: actions/checkout@v4
    - run: |
        brew install dlib
        ls -l /usr/local/lib/cmake/dlib
        grep -nr system /usr/local/lib/cmake/dlib
    - run: |
        cmake \
        -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=32 -DBUILD_PYTHON=OFF .
        make install -j3 VERBOSE=1
        make t_Dlib_std
        OPENTURNS_NUM_THREADS=2 OMP_NUM_THREADS=1 ctest -R Dlib_std -j3 --output-on-failure --timeout 100 --schedule-random
