on:
  push:
  pull_request:
jobs:
  macos:
    runs-on: macos-latest
    env:
      LDFLAGS: -L/opt/homebrew/opt/openblas/lib
      CPPFLAGS: -I/opt/homebrew/opt/openblas/include
    steps:
    - uses: actions/checkout@v4
    - run: |
        brew install openblas swig boost python3 tbb nlopt cminpack ceres-solver bison flex hdf5 ipopt primesieve spectra pagmo cuba nanoflann
        pip3 install matplotlib scipy chaospy pandas dill --break-system-packages
    - run: |
        cmake \
        -DCMAKE_INSTALL_PREFIX=~/.local \
        -DPython_EXECUTABLE=/opt/homebrew/bin/python3 \
        -DUSE_BISON=OFF \
        -DFLEX_EXECUTABLE=/opt/homebrew/opt/flex/bin/flex \
        -DBISON_EXECUTABLE=/opt/homebrew/opt/bison/bin/bison \
        -DCMAKE_CXX_FLAGS="-Wall -Wextra -Werror" \
        -DCMAKE_SWIG_FLAGS="-Werror" -DSWIG_COMPILE_FLAGS="-O1 -Wno-unused-parameter -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-field-initializers" \
        -DCMAKE_UNITY_BUILD=ON -DCMAKE_UNITY_BUILD_BATCH_SIZE=32 .
        make install -j3
        make tests -j3
        OPENTURNS_NUM_THREADS=2 OMP_NUM_THREADS=1 ctest -E GeneralizedParetoFactory_std -j3 --output-on-failure --timeout 100 --schedule-random

