name: Lint source code

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIP_BREAK_SYSTEM_PACKAGES: 1
    steps:
    - uses: actions/checkout@v4
    - name: Install
      run: |
        sudo apt-get install -y python3-pip lintian
        pip3 install flake8 doc8
    - name: Run linter 
      run: ./utils/lint.sh

